quarkus:
  native:
    additional-build-args:
      - "--initialize-at-run-time=com.github.f4b6a3.uuid.util.internal.RandomUtil$SecureRandomPool"
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:lumimoney-api}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  hibernate-orm:
    database:
      generation: ${DATABASE_GENERATION:update}
  http:
    auth:
      permission:
        authenticated:
          paths: /*
          policy: authenticated
    cors:
        ~: true
        origins: "*"
        methods: "GET,PUT,POST,DELETE,PATCH,OPTIONS"
        headers: "*"

  oidc:
    auth-server-url: https://auth.thiagosol.com/realms/thiagosol.com
    client-id: lumimoney-api
    credentials:
      secret: ${AUTH_CLIENT_SECRET}
    application-type: service
    roles:
      source: accesstoken
